name: Daily Toot with Secrets

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  toot-daily:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Run Toot script
      run: python main.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
